component:
  name: component_2
  template:
    resource:
      aws_ssm_parameter:
        component_2:
          name: ${var.component_2_name}
          type: ${var.component_2_type}
          value: ${var.component_2_value}
    variable:
      component_2_name:
        type: string
      component_2_type:
        type: string
      component_2_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_2.id}
      thub_id:
        value: ${aws_ssm_parameter.component_2.id}
      key_id:
        value: ${aws_ssm_parameter.component_2.key_id}
      version:
        value: ${aws_ssm_parameter.component_2.version}
      arn:
        value: ${aws_ssm_parameter.component_2.arn}
    tfvars:
      component_2_name: component_2
      component_2_type: String
      component_2_value: component_2
