component:
  name: component_17
  template:
    resource:
      aws_ssm_parameter:
        component_17:
          name: var.component_17_name
          type: var.component_17_type
          value: var.component_17_value
    variable:
      component_17_name:
        type: string
      component_17_type:
        type: string
      component_17_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.component_17.id
      thub_id:
        value: aws_ssm_parameter.component_17.id
      key_id:
        value: aws_ssm_parameter.component_17.key_id
      version:
        value: aws_ssm_parameter.component_17.version
      arn:
        value: aws_ssm_parameter.component_17.arn
    tfvars:
      component_17_name: component_17
      component_17_type: String
      component_17_value: component_17
