component:
  name: snsm_component_4
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_4:
          name: var.snsm_component_4_name
          type: var.snsm_component_4_type
          value: var.snsm_component_4_value
    variable:
      snsm_component_4_name:
        type: string
      snsm_component_4_type:
        type: string
      snsm_component_4_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_4.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_4.id
      key_id:
        value: aws_ssm_parameter.snsm_component_4.key_id
      version:
        value: aws_ssm_parameter.snsm_component_4.version
      arn:
        value: aws_ssm_parameter.snsm_component_4.arn
    tfvars:
      snsm_component_4_name: snsm_component_4
      snsm_component_4_type: String
      snsm_component_4_value: snsm_component_4
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_4/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
