component:
  name: component_4
  template:
    resource:
      aws_ssm_parameter:
        component_4:
          name: var.component_4_name
          type: var.component_4_type
          value: var.component_4_value
    variable:
      component_4_name:
        type: string
      component_4_type:
        type: string
      component_4_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.component_4.id
      thub_id:
        value: aws_ssm_parameter.component_4.id
      key_id:
        value: aws_ssm_parameter.component_4.key_id
      version:
        value: aws_ssm_parameter.component_4.version
      arn:
        value: aws_ssm_parameter.component_4.arn
    tfvars:
      component_4_name: component_4
      component_4_type: String
      component_4_value: component_4
