component:
  name: component_51
  template:
    resource:
      aws_ssm_parameter:
        component_51:
          name: ${var.component_51_name}
          type: ${var.component_51_type}
          value: ${var.component_51_value}
    variable:
      component_51_name:
        type: string
      component_51_type:
        type: string
      component_51_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_51.id}
      thub_id:
        value: ${aws_ssm_parameter.component_51.id}
      key_id:
        value: ${aws_ssm_parameter.component_51.key_id}
      version:
        value: ${aws_ssm_parameter.component_51.version}
      arn:
        value: ${aws_ssm_parameter.component_51.arn}
    tfvars:
      component_51_name: component_51
      component_51_type: String
      component_51_value: component_51
