component:
  name: component_28
  template:
    resource:
      aws_ssm_parameter:
        component_28:
          name: var.component_28_name
          type: var.component_28_type
          value: var.component_28_value
    variable:
      component_28_name:
        type: string
      component_28_type:
        type: string
      component_28_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.component_28.id
      thub_id:
        value: aws_ssm_parameter.component_28.id
      key_id:
        value: aws_ssm_parameter.component_28.key_id
      version:
        value: aws_ssm_parameter.component_28.version
      arn:
        value: aws_ssm_parameter.component_28.arn
    tfvars:
      component_28_name: component_28
      component_28_type: String
      component_28_value: component_28
