component:
  name: snsm_component_28
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_28:
          name: var.snsm_component_28_name
          type: var.snsm_component_28_type
          value: var.snsm_component_28_value
    variable:
      snsm_component_28_name:
        type: string
      snsm_component_28_type:
        type: string
      snsm_component_28_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_28.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_28.id
      key_id:
        value: aws_ssm_parameter.snsm_component_28.key_id
      version:
        value: aws_ssm_parameter.snsm_component_28.version
      arn:
        value: aws_ssm_parameter.snsm_component_28.arn
    tfvars:
      snsm_component_28_name: snsm_component_28
      snsm_component_28_type: String
      snsm_component_28_value: snsm_component_28
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_28/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
