component:
  name: component_71
  template:
    resource:
      aws_ssm_parameter:
        component_71:
          name: var.component_71_name
          type: var.component_71_type
          value: var.component_71_value
    variable:
      component_71_name:
        type: string
      component_71_type:
        type: string
      component_71_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.component_71.id
      thub_id:
        value: aws_ssm_parameter.component_71.id
      key_id:
        value: aws_ssm_parameter.component_71.key_id
      version:
        value: aws_ssm_parameter.component_71.version
      arn:
        value: aws_ssm_parameter.component_71.arn
    tfvars:
      component_71_name: component_71
      component_71_type: String
      component_71_value: component_71
