component:
  name: snsm_component_71
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_71:
          name: var.snsm_component_71_name
          type: var.snsm_component_71_type
          value: var.snsm_component_71_value
    variable:
      snsm_component_71_name:
        type: string
      snsm_component_71_type:
        type: string
      snsm_component_71_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_71.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_71.id
      key_id:
        value: aws_ssm_parameter.snsm_component_71.key_id
      version:
        value: aws_ssm_parameter.snsm_component_71.version
      arn:
        value: aws_ssm_parameter.snsm_component_71.arn
    tfvars:
      snsm_component_71_name: snsm_component_71
      snsm_component_71_type: String
      snsm_component_71_value: snsm_component_71
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_71/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
