component:
  name: component_69
  template:
    resource:
      aws_ssm_parameter:
        component_69:
          name: ${var.component_69_name}
          type: ${var.component_69_type}
          value: ${var.component_69_value}
    variable:
      component_69_name:
        type: string
      component_69_type:
        type: string
      component_69_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_69.id}
      thub_id:
        value: ${aws_ssm_parameter.component_69.id}
      key_id:
        value: ${aws_ssm_parameter.component_69.key_id}
      version:
        value: ${aws_ssm_parameter.component_69.version}
      arn:
        value: ${aws_ssm_parameter.component_69.arn}
    tfvars:
      component_69_name: component_69
      component_69_type: String
      component_69_value: component_69
