component:
  name: component_97
  template:
    resource:
      aws_ssm_parameter:
        component_97:
          name: var.component_97_name
          type: var.component_97_type
          value: var.component_97_value
    variable:
      component_97_name:
        type: string
      component_97_type:
        type: string
      component_97_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.component_97.id
      thub_id:
        value: aws_ssm_parameter.component_97.id
      key_id:
        value: aws_ssm_parameter.component_97.key_id
      version:
        value: aws_ssm_parameter.component_97.version
      arn:
        value: aws_ssm_parameter.component_97.arn
    tfvars:
      component_97_name: component_97
      component_97_type: String
      component_97_value: component_97
