component:
  name: snsm_component_31
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_31:
          name: var.snsm_component_31_name
          type: var.snsm_component_31_type
          value: var.snsm_component_31_value
    variable:
      snsm_component_31_name:
        type: string
      snsm_component_31_type:
        type: string
      snsm_component_31_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_31.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_31.id
      key_id:
        value: aws_ssm_parameter.snsm_component_31.key_id
      version:
        value: aws_ssm_parameter.snsm_component_31.version
      arn:
        value: aws_ssm_parameter.snsm_component_31.arn
    tfvars:
      snsm_component_31_name: snsm_component_31
      snsm_component_31_type: String
      snsm_component_31_value: snsm_component_31
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_31/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
