component:
  name: snsm_component_55
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_55:
          name: var.snsm_component_55_name
          type: var.snsm_component_55_type
          value: var.snsm_component_55_value
    variable:
      snsm_component_55_name:
        type: string
      snsm_component_55_type:
        type: string
      snsm_component_55_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_55.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_55.id
      key_id:
        value: aws_ssm_parameter.snsm_component_55.key_id
      version:
        value: aws_ssm_parameter.snsm_component_55.version
      arn:
        value: aws_ssm_parameter.snsm_component_55.arn
    tfvars:
      snsm_component_55_name: snsm_component_55
      snsm_component_55_type: String
      snsm_component_55_value: snsm_component_55
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_55/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
