component:
  name: component_55
  template:
    resource:
      aws_ssm_parameter:
        component_55:
          name: var.component_55_name
          type: var.component_55_type
          value: var.component_55_value
    variable:
      component_55_name:
        type: string
      component_55_type:
        type: string
      component_55_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.component_55.id
      thub_id:
        value: aws_ssm_parameter.component_55.id
      key_id:
        value: aws_ssm_parameter.component_55.key_id
      version:
        value: aws_ssm_parameter.component_55.version
      arn:
        value: aws_ssm_parameter.component_55.arn
    tfvars:
      component_55_name: component_55
      component_55_type: String
      component_55_value: component_55
