component:
  name: snsm_component_13
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_13:
          name: var.snsm_component_13_name
          type: var.snsm_component_13_type
          value: var.snsm_component_13_value
    variable:
      snsm_component_13_name:
        type: string
      snsm_component_13_type:
        type: string
      snsm_component_13_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_13.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_13.id
      key_id:
        value: aws_ssm_parameter.snsm_component_13.key_id
      version:
        value: aws_ssm_parameter.snsm_component_13.version
      arn:
        value: aws_ssm_parameter.snsm_component_13.arn
    tfvars:
      snsm_component_13_name: snsm_component_13
      snsm_component_13_type: String
      snsm_component_13_value: snsm_component_13
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_13/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
