component:
  name: component_83
  template:
    resource:
      aws_ssm_parameter:
        component_83:
          name: var.component_83_name
          type: var.component_83_type
          value: var.component_83_value
    variable:
      component_83_name:
        type: string
      component_83_type:
        type: string
      component_83_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.component_83.id
      thub_id:
        value: aws_ssm_parameter.component_83.id
      key_id:
        value: aws_ssm_parameter.component_83.key_id
      version:
        value: aws_ssm_parameter.component_83.version
      arn:
        value: aws_ssm_parameter.component_83.arn
    tfvars:
      component_83_name: component_83
      component_83_type: String
      component_83_value: component_83
