component:
  name: component_12
  template:
    resource:
      aws_ssm_parameter:
        component_12:
          name: var.component_12_name
          type: var.component_12_type
          value: var.component_12_value
    variable:
      component_12_name:
        type: string
      component_12_type:
        type: string
      component_12_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.component_12.id
      thub_id:
        value: aws_ssm_parameter.component_12.id
      key_id:
        value: aws_ssm_parameter.component_12.key_id
      version:
        value: aws_ssm_parameter.component_12.version
      arn:
        value: aws_ssm_parameter.component_12.arn
    tfvars:
      component_12_name: component_12
      component_12_type: String
      component_12_value: component_12
