component:
  name: component_144
  template:
    resource:
      aws_ssm_parameter:
        component_144:
          name: ${var.component_144_name}
          type: ${var.component_144_type}
          value: ${var.component_144_value}
    variable:
      component_144_name:
        type: string
      component_144_type:
        type: string
      component_144_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_144.id}
      thub_id:
        value: ${aws_ssm_parameter.component_144.id}
      key_id:
        value: ${aws_ssm_parameter.component_144.key_id}
      version:
        value: ${aws_ssm_parameter.component_144.version}
      arn:
        value: ${aws_ssm_parameter.component_144.arn}
    tfvars:
      component_144_name: component_144
      component_144_type: String
      component_144_value: component_144
