component:
  name: component_23
  template:
    resource:
      aws_ssm_parameter:
        component_23:
          name: var.component_23_name
          type: var.component_23_type
          value: var.component_23_value
    variable:
      component_23_name:
        type: string
      component_23_type:
        type: string
      component_23_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.component_23.id
      thub_id:
        value: aws_ssm_parameter.component_23.id
      key_id:
        value: aws_ssm_parameter.component_23.key_id
      version:
        value: aws_ssm_parameter.component_23.version
      arn:
        value: aws_ssm_parameter.component_23.arn
    tfvars:
      component_23_name: component_23
      component_23_type: String
      component_23_value: component_23
