component:
  name: snsm_component_10
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_10:
          name: var.snsm_component_10_name
          type: var.snsm_component_10_type
          value: var.snsm_component_10_value
    variable:
      snsm_component_10_name:
        type: string
      snsm_component_10_type:
        type: string
      snsm_component_10_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_10.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_10.id
      key_id:
        value: aws_ssm_parameter.snsm_component_10.key_id
      version:
        value: aws_ssm_parameter.snsm_component_10.version
      arn:
        value: aws_ssm_parameter.snsm_component_10.arn
    tfvars:
      snsm_component_10_name: snsm_component_10
      snsm_component_10_type: String
      snsm_component_10_value: snsm_component_10
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_10/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
