component:
  name: component_73
  template:
    resource:
      aws_ssm_parameter:
        component_73:
          name: var.component_73_name
          type: var.component_73_type
          value: var.component_73_value
    variable:
      component_73_name:
        type: string
      component_73_type:
        type: string
      component_73_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.component_73.id
      thub_id:
        value: aws_ssm_parameter.component_73.id
      key_id:
        value: aws_ssm_parameter.component_73.key_id
      version:
        value: aws_ssm_parameter.component_73.version
      arn:
        value: aws_ssm_parameter.component_73.arn
    tfvars:
      component_73_name: component_73
      component_73_type: String
      component_73_value: component_73
