component:
  name: component_178
  template:
    resource:
      aws_ssm_parameter:
        component_178:
          name: ${var.component_178_name}
          type: ${var.component_178_type}
          value: ${var.component_178_value}
    variable:
      component_178_name:
        type: string
      component_178_type:
        type: string
      component_178_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_178.id}
      thub_id:
        value: ${aws_ssm_parameter.component_178.id}
      key_id:
        value: ${aws_ssm_parameter.component_178.key_id}
      version:
        value: ${aws_ssm_parameter.component_178.version}
      arn:
        value: ${aws_ssm_parameter.component_178.arn}
    tfvars:
      component_178_name: component_178
      component_178_type: String
      component_178_value: component_178
