component:
  name: component_10
  template:
    resource:
      aws_ssm_parameter:
        component_10:
          name: var.component_10_name
          type: var.component_10_type
          value: var.component_10_value
    variable:
      component_10_name:
        type: string
      component_10_type:
        type: string
      component_10_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.component_10.id
      thub_id:
        value: aws_ssm_parameter.component_10.id
      key_id:
        value: aws_ssm_parameter.component_10.key_id
      version:
        value: aws_ssm_parameter.component_10.version
      arn:
        value: aws_ssm_parameter.component_10.arn
    tfvars:
      component_10_name: component_10
      component_10_type: String
      component_10_value: component_10
