component:
  name: component_16
  template:
    resource:
      aws_ssm_parameter:
        component_16:
          name: ${var.component_16_name}
          type: ${var.component_16_type}
          value: ${var.component_16_value}
    variable:
      component_16_name:
        type: string
      component_16_type:
        type: string
      component_16_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_16.id}
      thub_id:
        value: ${aws_ssm_parameter.component_16.id}
      key_id:
        value: ${aws_ssm_parameter.component_16.key_id}
      version:
        value: ${aws_ssm_parameter.component_16.version}
      arn:
        value: ${aws_ssm_parameter.component_16.arn}
    tfvars:
      component_16_name: component_16
      component_16_type: String
      component_16_value: component_16
