component:
  name: snsm_component_89
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_89:
          name: var.snsm_component_89_name
          type: var.snsm_component_89_type
          value: var.snsm_component_89_value
    variable:
      snsm_component_89_name:
        type: string
      snsm_component_89_type:
        type: string
      snsm_component_89_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_89.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_89.id
      key_id:
        value: aws_ssm_parameter.snsm_component_89.key_id
      version:
        value: aws_ssm_parameter.snsm_component_89.version
      arn:
        value: aws_ssm_parameter.snsm_component_89.arn
    tfvars:
      snsm_component_89_name: snsm_component_89
      snsm_component_89_type: String
      snsm_component_89_value: snsm_component_89
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_89/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
