component:
  name: component_89
  template:
    resource:
      aws_ssm_parameter:
        component_89:
          name: var.component_89_name
          type: var.component_89_type
          value: var.component_89_value
    variable:
      component_89_name:
        type: string
      component_89_type:
        type: string
      component_89_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.component_89.id
      thub_id:
        value: aws_ssm_parameter.component_89.id
      key_id:
        value: aws_ssm_parameter.component_89.key_id
      version:
        value: aws_ssm_parameter.component_89.version
      arn:
        value: aws_ssm_parameter.component_89.arn
    tfvars:
      component_89_name: component_89
      component_89_type: String
      component_89_value: component_89
