component:
  name: snsm_component_46
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_46:
          name: var.snsm_component_46_name
          type: var.snsm_component_46_type
          value: var.snsm_component_46_value
    variable:
      snsm_component_46_name:
        type: string
      snsm_component_46_type:
        type: string
      snsm_component_46_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_46.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_46.id
      key_id:
        value: aws_ssm_parameter.snsm_component_46.key_id
      version:
        value: aws_ssm_parameter.snsm_component_46.version
      arn:
        value: aws_ssm_parameter.snsm_component_46.arn
    tfvars:
      snsm_component_46_name: snsm_component_46
      snsm_component_46_type: String
      snsm_component_46_value: snsm_component_46
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_46/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
