component:
  name: component_46
  template:
    resource:
      aws_ssm_parameter:
        component_46:
          name: ${var.component_46_name}
          type: ${var.component_46_type}
          value: ${var.component_46_value}
    variable:
      component_46_name:
        type: string
      component_46_type:
        type: string
      component_46_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_46.id}
      thub_id:
        value: ${aws_ssm_parameter.component_46.id}
      key_id:
        value: ${aws_ssm_parameter.component_46.key_id}
      version:
        value: ${aws_ssm_parameter.component_46.version}
      arn:
        value: ${aws_ssm_parameter.component_46.arn}
    tfvars:
      component_46_name: component_46
      component_46_type: String
      component_46_value: component_46
