component:
  name: snsm_component_59
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_59:
          name: var.snsm_component_59_name
          type: var.snsm_component_59_type
          value: var.snsm_component_59_value
    variable:
      snsm_component_59_name:
        type: string
      snsm_component_59_type:
        type: string
      snsm_component_59_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_59.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_59.id
      key_id:
        value: aws_ssm_parameter.snsm_component_59.key_id
      version:
        value: aws_ssm_parameter.snsm_component_59.version
      arn:
        value: aws_ssm_parameter.snsm_component_59.arn
    tfvars:
      snsm_component_59_name: snsm_component_59
      snsm_component_59_type: String
      snsm_component_59_value: snsm_component_59
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_59/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
