component:
  name: component_59
  template:
    resource:
      aws_ssm_parameter:
        component_59:
          name: ${var.component_59_name}
          type: ${var.component_59_type}
          value: ${var.component_59_value}
    variable:
      component_59_name:
        type: string
      component_59_type:
        type: string
      component_59_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_59.id}
      thub_id:
        value: ${aws_ssm_parameter.component_59.id}
      key_id:
        value: ${aws_ssm_parameter.component_59.key_id}
      version:
        value: ${aws_ssm_parameter.component_59.version}
      arn:
        value: ${aws_ssm_parameter.component_59.arn}
    tfvars:
      component_59_name: component_59
      component_59_type: String
      component_59_value: component_59
