component:
  name: snsm_component_16
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_16:
          name: var.snsm_component_16_name
          type: var.snsm_component_16_type
          value: var.snsm_component_16_value
    variable:
      snsm_component_16_name:
        type: string
      snsm_component_16_type:
        type: string
      snsm_component_16_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_16.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_16.id
      key_id:
        value: aws_ssm_parameter.snsm_component_16.key_id
      version:
        value: aws_ssm_parameter.snsm_component_16.version
      arn:
        value: aws_ssm_parameter.snsm_component_16.arn
    tfvars:
      snsm_component_16_name: snsm_component_16
      snsm_component_16_type: String
      snsm_component_16_value: snsm_component_16
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_16/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
