component:
  name: component_129
  template:
    resource:
      aws_ssm_parameter:
        component_129:
          name: ${var.component_129_name}
          type: ${var.component_129_type}
          value: ${var.component_129_value}
    variable:
      component_129_name:
        type: string
      component_129_type:
        type: string
      component_129_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_129.id}
      thub_id:
        value: ${aws_ssm_parameter.component_129.id}
      key_id:
        value: ${aws_ssm_parameter.component_129.key_id}
      version:
        value: ${aws_ssm_parameter.component_129.version}
      arn:
        value: ${aws_ssm_parameter.component_129.arn}
    tfvars:
      component_129_name: component_129
      component_129_type: String
      component_129_value: component_129
