project:
  name: demo-cloud-deployer
  code: 12Yd66g
  distributor: lambda
terraform:
  varFile:
    - default.tfvars
  version: 0.11.14
  cloudAccount: default
template:
  provider:
    aws:
      region: us-east-1
      allowed_account_ids:
        - 722084099005
  terraform:
    backend:
      s3:
        key: terraform/demo_cloud_deployer_11/${tfvar.terrahub["component"]["name"]}/terraform.tfstate
        bucket: terraform-aws-landing-zone-mitocgroup
        region: us-east-1
