project:
  name: demo-cloud-deployer
  code: 12Yd66g
  distributor: lambda
terraform:
  varFile:
    - default.tfvars
  version: 0.12.13
  cloudAccount: default
  backendAccount: default
template:
  provider:
    aws:
      region: us-east-1
      allowed_account_ids:
        - 123456789012
  terraform:
    backend:
      s3:
        key: terraform/demo_cloud_deployer/${tfvar.terrahub["component"]["name"]}/terraform.tfstate
        bucket: terraform-aws-landing-zone
        region: us-east-1
