project:
  name: cloud-deployer-demo
  code: 12Yd66g
  distributor: lambda
terraform:
  varFile:
    - default.tfvars
  version: '0.12.9'
  cloudAccount: terrahub
  backendAccount: terrahub

template:
  provider:
    aws:
      region: us-east-1
      allowed_account_ids:
        - 600605919324
