project:
  name: demo-cloud-deployer
  code: 12Yd66g
  distributor: lambda
terraform:
  varFile:
    - default.tfvars
  version: 0.12.13
  cloudAccount: terrahub
  backendAccount: terrahub
template:
  provider:
    aws:
      region: us-east-1
      allowed_account_ids:
        - 123456789012
