component:
  name: component_96
  template:
    resource:
      aws_ssm_parameter:
        component_96:
          name: ${var.component_96_name}
          type: ${var.component_96_type}
          value: ${var.component_96_value}
    variable:
      component_96_name:
        type: string
      component_96_type:
        type: string
      component_96_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_96.id}
      thub_id:
        value: ${aws_ssm_parameter.component_96.id}
      key_id:
        value: ${aws_ssm_parameter.component_96.key_id}
      version:
        value: ${aws_ssm_parameter.component_96.version}
      arn:
        value: ${aws_ssm_parameter.component_96.arn}
    tfvars:
      component_96_name: component_96
      component_96_type: String
      component_96_value: component_96
