component:
  name: component_65
  template:
    resource:
      aws_ssm_parameter:
        component_65:
          name: ${var.component_65_name}
          type: ${var.component_65_type}
          value: ${var.component_65_value}
    variable:
      component_65_name:
        type: string
      component_65_type:
        type: string
      component_65_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_65.id}
      thub_id:
        value: ${aws_ssm_parameter.component_65.id}
      key_id:
        value: ${aws_ssm_parameter.component_65.key_id}
      version:
        value: ${aws_ssm_parameter.component_65.version}
      arn:
        value: ${aws_ssm_parameter.component_65.arn}
    tfvars:
      component_65_name: component_65
      component_65_type: String
      component_65_value: component_65
