component:
  name: snsm_component_65
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_65:
          name: var.snsm_component_65_name
          type: var.snsm_component_65_type
          value: var.snsm_component_65_value
    variable:
      snsm_component_65_name:
        type: string
      snsm_component_65_type:
        type: string
      snsm_component_65_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_65.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_65.id
      key_id:
        value: aws_ssm_parameter.snsm_component_65.key_id
      version:
        value: aws_ssm_parameter.snsm_component_65.version
      arn:
        value: aws_ssm_parameter.snsm_component_65.arn
    tfvars:
      snsm_component_65_name: snsm_component_65
      snsm_component_65_type: String
      snsm_component_65_value: snsm_component_65
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_65/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
