component:
  name: component_6
  template:
    resource:
      aws_ssm_parameter:
        component_6:
          name: var.component_6_name
          type: var.component_6_type
          value: var.component_6_value
    variable:
      component_6_name:
        type: string
      component_6_type:
        type: string
      component_6_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.component_6.id
      thub_id:
        value: aws_ssm_parameter.component_6.id
      key_id:
        value: aws_ssm_parameter.component_6.key_id
      version:
        value: aws_ssm_parameter.component_6.version
      arn:
        value: aws_ssm_parameter.component_6.arn
    tfvars:
      component_6_name: component_6
      component_6_type: String
      component_6_value: component_6
