component:
  name: component_36
  template:
    resource:
      aws_ssm_parameter:
        component_36:
          name: ${var.component_36_name}
          type: ${var.component_36_type}
          value: ${var.component_36_value}
    variable:
      component_36_name:
        type: string
      component_36_type:
        type: string
      component_36_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_36.id}
      thub_id:
        value: ${aws_ssm_parameter.component_36.id}
      key_id:
        value: ${aws_ssm_parameter.component_36.key_id}
      version:
        value: ${aws_ssm_parameter.component_36.version}
      arn:
        value: ${aws_ssm_parameter.component_36.arn}
    tfvars:
      component_36_name: component_36
      component_36_type: String
      component_36_value: component_36
