component:
  name: component_8
  template:
    resource:
      aws_ssm_parameter:
        component_8:
          name: ${var.component_8_name}
          type: ${var.component_8_type}
          value: ${var.component_8_value}
    variable:
      component_8_name:
        type: string
      component_8_type:
        type: string
      component_8_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_8.id}
      thub_id:
        value: ${aws_ssm_parameter.component_8.id}
      key_id:
        value: ${aws_ssm_parameter.component_8.key_id}
      version:
        value: ${aws_ssm_parameter.component_8.version}
      arn:
        value: ${aws_ssm_parameter.component_8.arn}
    tfvars:
      component_8_name: component_8
      component_8_type: String
      component_8_value: component_8
