component:
  name: component_80
  template:
    resource:
      aws_ssm_parameter:
        component_80:
          name: ${var.component_80_name}
          type: ${var.component_80_type}
          value: ${var.component_80_value}
    variable:
      component_80_name:
        type: string
      component_80_type:
        type: string
      component_80_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_80.id}
      thub_id:
        value: ${aws_ssm_parameter.component_80.id}
      key_id:
        value: ${aws_ssm_parameter.component_80.key_id}
      version:
        value: ${aws_ssm_parameter.component_80.version}
      arn:
        value: ${aws_ssm_parameter.component_80.arn}
    tfvars:
      component_80_name: component_80
      component_80_type: String
      component_80_value: component_80
