component:
  name: snsm_component_93
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_93:
          name: var.snsm_component_93_name
          type: var.snsm_component_93_type
          value: var.snsm_component_93_value
    variable:
      snsm_component_93_name:
        type: string
      snsm_component_93_type:
        type: string
      snsm_component_93_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_93.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_93.id
      key_id:
        value: aws_ssm_parameter.snsm_component_93.key_id
      version:
        value: aws_ssm_parameter.snsm_component_93.version
      arn:
        value: aws_ssm_parameter.snsm_component_93.arn
    tfvars:
      snsm_component_93_name: snsm_component_93
      snsm_component_93_type: String
      snsm_component_93_value: snsm_component_93
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_93/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
