component:
  name: component_98
  template:
    resource:
      aws_ssm_parameter:
        component_98:
          name: ${var.component_98_name}
          type: ${var.component_98_type}
          value: ${var.component_98_value}
    variable:
      component_98_name:
        type: string
      component_98_type:
        type: string
      component_98_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_98.id}
      thub_id:
        value: ${aws_ssm_parameter.component_98.id}
      key_id:
        value: ${aws_ssm_parameter.component_98.key_id}
      version:
        value: ${aws_ssm_parameter.component_98.version}
      arn:
        value: ${aws_ssm_parameter.component_98.arn}
    tfvars:
      component_98_name: component_98
      component_98_type: String
      component_98_value: component_98
