component:
  name: component_26
  template:
    resource:
      aws_ssm_parameter:
        component_26:
          name: ${var.component_26_name}
          type: ${var.component_26_type}
          value: ${var.component_26_value}
    variable:
      component_26_name:
        type: string
      component_26_type:
        type: string
      component_26_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_26.id}
      thub_id:
        value: ${aws_ssm_parameter.component_26.id}
      key_id:
        value: ${aws_ssm_parameter.component_26.key_id}
      version:
        value: ${aws_ssm_parameter.component_26.version}
      arn:
        value: ${aws_ssm_parameter.component_26.arn}
    tfvars:
      component_26_name: component_26
      component_26_type: String
      component_26_value: component_26
