component:
  name: component_190
  template:
    resource:
      aws_ssm_parameter:
        component_190:
          name: ${var.component_190_name}
          type: ${var.component_190_type}
          value: ${var.component_190_value}
    variable:
      component_190_name:
        type: string
      component_190_type:
        type: string
      component_190_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_190.id}
      thub_id:
        value: ${aws_ssm_parameter.component_190.id}
      key_id:
        value: ${aws_ssm_parameter.component_190.key_id}
      version:
        value: ${aws_ssm_parameter.component_190.version}
      arn:
        value: ${aws_ssm_parameter.component_190.arn}
    tfvars:
      component_190_name: component_190
      component_190_type: String
      component_190_value: component_190
