component:
  name: component_74
  template:
    resource:
      aws_ssm_parameter:
        component_74:
          name: ${var.component_74_name}
          type: ${var.component_74_type}
          value: ${var.component_74_value}
    variable:
      component_74_name:
        type: string
      component_74_type:
        type: string
      component_74_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_74.id}
      thub_id:
        value: ${aws_ssm_parameter.component_74.id}
      key_id:
        value: ${aws_ssm_parameter.component_74.key_id}
      version:
        value: ${aws_ssm_parameter.component_74.version}
      arn:
        value: ${aws_ssm_parameter.component_74.arn}
    tfvars:
      component_74_name: component_74
      component_74_type: String
      component_74_value: component_74
