component:
  name: snsm_component_92
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_92:
          name: var.snsm_component_92_name
          type: var.snsm_component_92_type
          value: var.snsm_component_92_value
    variable:
      snsm_component_92_name:
        type: string
      snsm_component_92_type:
        type: string
      snsm_component_92_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_92.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_92.id
      key_id:
        value: aws_ssm_parameter.snsm_component_92.key_id
      version:
        value: aws_ssm_parameter.snsm_component_92.version
      arn:
        value: aws_ssm_parameter.snsm_component_92.arn
    tfvars:
      snsm_component_92_name: snsm_component_92
      snsm_component_92_type: String
      snsm_component_92_value: snsm_component_92
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_92/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
