component:
  name: snsm_component_3
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_3:
          name: var.snsm_component_3_name
          type: var.snsm_component_3_type
          value: var.snsm_component_3_value
    variable:
      snsm_component_3_name:
        type: string
      snsm_component_3_type:
        type: string
      snsm_component_3_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_3.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_3.id
      key_id:
        value: aws_ssm_parameter.snsm_component_3.key_id
      version:
        value: aws_ssm_parameter.snsm_component_3.version
      arn:
        value: aws_ssm_parameter.snsm_component_3.arn
    tfvars:
      snsm_component_3_name: snsm_component_3
      snsm_component_3_type: String
      snsm_component_3_value: snsm_component_3
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_3/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
