component:
  name: snsm_component_45
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_45:
          name: var.snsm_component_45_name
          type: var.snsm_component_45_type
          value: var.snsm_component_45_value
    variable:
      snsm_component_45_name:
        type: string
      snsm_component_45_type:
        type: string
      snsm_component_45_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_45.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_45.id
      key_id:
        value: aws_ssm_parameter.snsm_component_45.key_id
      version:
        value: aws_ssm_parameter.snsm_component_45.version
      arn:
        value: aws_ssm_parameter.snsm_component_45.arn
    tfvars:
      snsm_component_45_name: snsm_component_45
      snsm_component_45_type: String
      snsm_component_45_value: snsm_component_45
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_45/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
