component:
  name: component_45
  template:
    resource:
      aws_ssm_parameter:
        component_45:
          name: var.component_45_name
          type: var.component_45_type
          value: var.component_45_value
    variable:
      component_45_name:
        type: string
      component_45_type:
        type: string
      component_45_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.component_45.id
      thub_id:
        value: aws_ssm_parameter.component_45.id
      key_id:
        value: aws_ssm_parameter.component_45.key_id
      version:
        value: aws_ssm_parameter.component_45.version
      arn:
        value: aws_ssm_parameter.component_45.arn
    tfvars:
      component_45_name: component_45
      component_45_type: String
      component_45_value: component_45
