component:
  name: snsm_component_50
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_50:
          name: var.snsm_component_50_name
          type: var.snsm_component_50_type
          value: var.snsm_component_50_value
    variable:
      snsm_component_50_name:
        type: string
      snsm_component_50_type:
        type: string
      snsm_component_50_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_50.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_50.id
      key_id:
        value: aws_ssm_parameter.snsm_component_50.key_id
      version:
        value: aws_ssm_parameter.snsm_component_50.version
      arn:
        value: aws_ssm_parameter.snsm_component_50.arn
    tfvars:
      snsm_component_50_name: snsm_component_50
      snsm_component_50_type: String
      snsm_component_50_value: snsm_component_50
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_50/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
