component:
  name: component_50
  template:
    resource:
      aws_ssm_parameter:
        component_50:
          name: ${var.component_50_name}
          type: ${var.component_50_type}
          value: ${var.component_50_value}
    variable:
      component_50_name:
        type: string
      component_50_type:
        type: string
      component_50_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_50.id}
      thub_id:
        value: ${aws_ssm_parameter.component_50.id}
      key_id:
        value: ${aws_ssm_parameter.component_50.key_id}
      version:
        value: ${aws_ssm_parameter.component_50.version}
      arn:
        value: ${aws_ssm_parameter.component_50.arn}
    tfvars:
      component_50_name: component_50
      component_50_type: String
      component_50_value: component_50
