component:
  name: snsm_component_21
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_21:
          name: var.snsm_component_21_name
          type: var.snsm_component_21_type
          value: var.snsm_component_21_value
    variable:
      snsm_component_21_name:
        type: string
      snsm_component_21_type:
        type: string
      snsm_component_21_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_21.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_21.id
      key_id:
        value: aws_ssm_parameter.snsm_component_21.key_id
      version:
        value: aws_ssm_parameter.snsm_component_21.version
      arn:
        value: aws_ssm_parameter.snsm_component_21.arn
    tfvars:
      snsm_component_21_name: snsm_component_21
      snsm_component_21_type: String
      snsm_component_21_value: snsm_component_21
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_21/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
