component:
  name: snsm_component_75
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_75:
          name: var.snsm_component_75_name
          type: var.snsm_component_75_type
          value: var.snsm_component_75_value
    variable:
      snsm_component_75_name:
        type: string
      snsm_component_75_type:
        type: string
      snsm_component_75_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_75.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_75.id
      key_id:
        value: aws_ssm_parameter.snsm_component_75.key_id
      version:
        value: aws_ssm_parameter.snsm_component_75.version
      arn:
        value: aws_ssm_parameter.snsm_component_75.arn
    tfvars:
      snsm_component_75_name: snsm_component_75
      snsm_component_75_type: String
      snsm_component_75_value: snsm_component_75
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_75/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
