component:
  name: snsm_component_64
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_64:
          name: var.snsm_component_64_name
          type: var.snsm_component_64_type
          value: var.snsm_component_64_value
    variable:
      snsm_component_64_name:
        type: string
      snsm_component_64_type:
        type: string
      snsm_component_64_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_64.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_64.id
      key_id:
        value: aws_ssm_parameter.snsm_component_64.key_id
      version:
        value: aws_ssm_parameter.snsm_component_64.version
      arn:
        value: aws_ssm_parameter.snsm_component_64.arn
    tfvars:
      snsm_component_64_name: snsm_component_64
      snsm_component_64_type: String
      snsm_component_64_value: snsm_component_64
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_64/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
