component:
  name: component_41
  template:
    resource:
      aws_ssm_parameter:
        component_41:
          name: var.component_41_name
          type: var.component_41_type
          value: var.component_41_value
    variable:
      component_41_name:
        type: string
      component_41_type:
        type: string
      component_41_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.component_41.id
      thub_id:
        value: aws_ssm_parameter.component_41.id
      key_id:
        value: aws_ssm_parameter.component_41.key_id
      version:
        value: aws_ssm_parameter.component_41.version
      arn:
        value: aws_ssm_parameter.component_41.arn
    tfvars:
      component_41_name: component_41
      component_41_type: String
      component_41_value: component_41
