component:
  name: snsm_component_41
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_41:
          name: var.snsm_component_41_name
          type: var.snsm_component_41_type
          value: var.snsm_component_41_value
    variable:
      snsm_component_41_name:
        type: string
      snsm_component_41_type:
        type: string
      snsm_component_41_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_41.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_41.id
      key_id:
        value: aws_ssm_parameter.snsm_component_41.key_id
      version:
        value: aws_ssm_parameter.snsm_component_41.version
      arn:
        value: aws_ssm_parameter.snsm_component_41.arn
    tfvars:
      snsm_component_41_name: snsm_component_41
      snsm_component_41_type: String
      snsm_component_41_value: snsm_component_41
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_41/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
