component:
  name: component_86
  template:
    resource:
      aws_ssm_parameter:
        component_86:
          name: ${var.component_86_name}
          type: ${var.component_86_type}
          value: ${var.component_86_value}
    variable:
      component_86_name:
        type: string
      component_86_type:
        type: string
      component_86_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_86.id}
      thub_id:
        value: ${aws_ssm_parameter.component_86.id}
      key_id:
        value: ${aws_ssm_parameter.component_86.key_id}
      version:
        value: ${aws_ssm_parameter.component_86.version}
      arn:
        value: ${aws_ssm_parameter.component_86.arn}
    tfvars:
      component_86_name: component_86
      component_86_type: String
      component_86_value: component_86
