component:
  name: snsm_component_11
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_11:
          name: var.snsm_component_11_name
          type: var.snsm_component_11_type
          value: var.snsm_component_11_value
    variable:
      snsm_component_11_name:
        type: string
      snsm_component_11_type:
        type: string
      snsm_component_11_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_11.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_11.id
      key_id:
        value: aws_ssm_parameter.snsm_component_11.key_id
      version:
        value: aws_ssm_parameter.snsm_component_11.version
      arn:
        value: aws_ssm_parameter.snsm_component_11.arn
    tfvars:
      snsm_component_11_name: snsm_component_11
      snsm_component_11_type: String
      snsm_component_11_value: snsm_component_11
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_11/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
