component:
  name: component_84
  template:
    resource:
      aws_ssm_parameter:
        component_84:
          name: ${var.component_84_name}
          type: ${var.component_84_type}
          value: ${var.component_84_value}
    variable:
      component_84_name:
        type: string
      component_84_type:
        type: string
      component_84_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_84.id}
      thub_id:
        value: ${aws_ssm_parameter.component_84.id}
      key_id:
        value: ${aws_ssm_parameter.component_84.key_id}
      version:
        value: ${aws_ssm_parameter.component_84.version}
      arn:
        value: ${aws_ssm_parameter.component_84.arn}
    tfvars:
      component_84_name: component_84
      component_84_type: String
      component_84_value: component_84
