component:
  name: component_60
  template:
    resource:
      aws_ssm_parameter:
        component_60:
          name: var.component_60_name
          type: var.component_60_type
          value: var.component_60_value
    variable:
      component_60_name:
        type: string
      component_60_type:
        type: string
      component_60_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.component_60.id
      thub_id:
        value: aws_ssm_parameter.component_60.id
      key_id:
        value: aws_ssm_parameter.component_60.key_id
      version:
        value: aws_ssm_parameter.component_60.version
      arn:
        value: aws_ssm_parameter.component_60.arn
    tfvars:
      component_60_name: component_60
      component_60_type: String
      component_60_value: component_60
