component:
  name: snsm_component_60
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_60:
          name: var.snsm_component_60_name
          type: var.snsm_component_60_type
          value: var.snsm_component_60_value
    variable:
      snsm_component_60_name:
        type: string
      snsm_component_60_type:
        type: string
      snsm_component_60_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_60.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_60.id
      key_id:
        value: aws_ssm_parameter.snsm_component_60.key_id
      version:
        value: aws_ssm_parameter.snsm_component_60.version
      arn:
        value: aws_ssm_parameter.snsm_component_60.arn
    tfvars:
      snsm_component_60_name: snsm_component_60
      snsm_component_60_type: String
      snsm_component_60_value: snsm_component_60
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_60/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
