component:
  name: component_33
  template:
    resource:
      aws_ssm_parameter:
        component_33:
          name: var.component_33_name
          type: var.component_33_type
          value: var.component_33_value
    variable:
      component_33_name:
        type: string
      component_33_type:
        type: string
      component_33_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.component_33.id
      thub_id:
        value: aws_ssm_parameter.component_33.id
      key_id:
        value: aws_ssm_parameter.component_33.key_id
      version:
        value: aws_ssm_parameter.component_33.version
      arn:
        value: aws_ssm_parameter.component_33.arn
    tfvars:
      component_33_name: component_33
      component_33_type: String
      component_33_value: component_33
