component:
  name: component_20
  template:
    resource:
      aws_ssm_parameter:
        component_20:
          name: ${var.component_20_name}
          type: ${var.component_20_type}
          value: ${var.component_20_value}
    variable:
      component_20_name:
        type: string
      component_20_type:
        type: string
      component_20_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_20.id}
      thub_id:
        value: ${aws_ssm_parameter.component_20.id}
      key_id:
        value: ${aws_ssm_parameter.component_20.key_id}
      version:
        value: ${aws_ssm_parameter.component_20.version}
      arn:
        value: ${aws_ssm_parameter.component_20.arn}
    tfvars:
      component_20_name: component_20
      component_20_type: String
      component_20_value: component_20
