component:
  name: snsm_component_20
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_20:
          name: var.snsm_component_20_name
          type: var.snsm_component_20_type
          value: var.snsm_component_20_value
    variable:
      snsm_component_20_name:
        type: string
      snsm_component_20_type:
        type: string
      snsm_component_20_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_20.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_20.id
      key_id:
        value: aws_ssm_parameter.snsm_component_20.key_id
      version:
        value: aws_ssm_parameter.snsm_component_20.version
      arn:
        value: aws_ssm_parameter.snsm_component_20.arn
    tfvars:
      snsm_component_20_name: snsm_component_20
      snsm_component_20_type: String
      snsm_component_20_value: snsm_component_20
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_20/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
