component:
  name: component_30
  template:
    resource:
      aws_ssm_parameter:
        component_30:
          name: var.component_30_name
          type: var.component_30_type
          value: var.component_30_value
    variable:
      component_30_name:
        type: string
      component_30_type:
        type: string
      component_30_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.component_30.id
      thub_id:
        value: aws_ssm_parameter.component_30.id
      key_id:
        value: aws_ssm_parameter.component_30.key_id
      version:
        value: aws_ssm_parameter.component_30.version
      arn:
        value: aws_ssm_parameter.component_30.arn
    tfvars:
      component_30_name: component_30
      component_30_type: String
      component_30_value: component_30
