component:
  name: component_48
  template:
    resource:
      aws_ssm_parameter:
        component_48:
          name: var.component_48_name
          type: var.component_48_type
          value: var.component_48_value
    variable:
      component_48_name:
        type: string
      component_48_type:
        type: string
      component_48_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.component_48.id
      thub_id:
        value: aws_ssm_parameter.component_48.id
      key_id:
        value: aws_ssm_parameter.component_48.key_id
      version:
        value: aws_ssm_parameter.component_48.version
      arn:
        value: aws_ssm_parameter.component_48.arn
    tfvars:
      component_48_name: component_48
      component_48_type: String
      component_48_value: component_48
