component:
  name: snsm_component_91
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_91:
          name: var.snsm_component_91_name
          type: var.snsm_component_91_type
          value: var.snsm_component_91_value
    variable:
      snsm_component_91_name:
        type: string
      snsm_component_91_type:
        type: string
      snsm_component_91_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_91.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_91.id
      key_id:
        value: aws_ssm_parameter.snsm_component_91.key_id
      version:
        value: aws_ssm_parameter.snsm_component_91.version
      arn:
        value: aws_ssm_parameter.snsm_component_91.arn
    tfvars:
      snsm_component_91_name: snsm_component_91
      snsm_component_91_type: String
      snsm_component_91_value: snsm_component_91
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_91/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
