component:
  name: snsm_component_85
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_85:
          name: var.snsm_component_85_name
          type: var.snsm_component_85_type
          value: var.snsm_component_85_value
    variable:
      snsm_component_85_name:
        type: string
      snsm_component_85_type:
        type: string
      snsm_component_85_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_85.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_85.id
      key_id:
        value: aws_ssm_parameter.snsm_component_85.key_id
      version:
        value: aws_ssm_parameter.snsm_component_85.version
      arn:
        value: aws_ssm_parameter.snsm_component_85.arn
    tfvars:
      snsm_component_85_name: snsm_component_85
      snsm_component_85_type: String
      snsm_component_85_value: snsm_component_85
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_85/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
