component:
  name: component_3
  template:
    resource:
      aws_ssm_parameter:
        component_3:
          name: var.component_3_name
          type: var.component_3_type
          value: var.component_3_value
    variable:
      component_3_name:
        type: string
      component_3_type:
        type: string
      component_3_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.component_3.id
      thub_id:
        value: aws_ssm_parameter.component_3.id
      key_id:
        value: aws_ssm_parameter.component_3.key_id
      version:
        value: aws_ssm_parameter.component_3.version
      arn:
        value: aws_ssm_parameter.component_3.arn
    tfvars:
      component_3_name: component_3
      component_3_type: String
      component_3_value: component_3
