component:
  name: component_39
  template:
    resource:
      aws_ssm_parameter:
        component_39:
          name: ${var.component_39_name}
          type: ${var.component_39_type}
          value: ${var.component_39_value}
    variable:
      component_39_name:
        type: string
      component_39_type:
        type: string
      component_39_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_39.id}
      thub_id:
        value: ${aws_ssm_parameter.component_39.id}
      key_id:
        value: ${aws_ssm_parameter.component_39.key_id}
      version:
        value: ${aws_ssm_parameter.component_39.version}
      arn:
        value: ${aws_ssm_parameter.component_39.arn}
    tfvars:
      component_39_name: component_39
      component_39_type: String
      component_39_value: component_39
