component:
  name: component_151
  template:
    resource:
      aws_ssm_parameter:
        component_151:
          name: ${var.component_151_name}
          type: ${var.component_151_type}
          value: ${var.component_151_value}
    variable:
      component_151_name:
        type: string
      component_151_type:
        type: string
      component_151_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_151.id}
      thub_id:
        value: ${aws_ssm_parameter.component_151.id}
      key_id:
        value: ${aws_ssm_parameter.component_151.key_id}
      version:
        value: ${aws_ssm_parameter.component_151.version}
      arn:
        value: ${aws_ssm_parameter.component_151.arn}
    tfvars:
      component_151_name: component_151
      component_151_type: String
      component_151_value: component_151
