component:
  name: component_124
  template:
    resource:
      aws_ssm_parameter:
        component_124:
          name: ${var.component_124_name}
          type: ${var.component_124_type}
          value: ${var.component_124_value}
    variable:
      component_124_name:
        type: string
      component_124_type:
        type: string
      component_124_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_124.id}
      thub_id:
        value: ${aws_ssm_parameter.component_124.id}
      key_id:
        value: ${aws_ssm_parameter.component_124.key_id}
      version:
        value: ${aws_ssm_parameter.component_124.version}
      arn:
        value: ${aws_ssm_parameter.component_124.arn}
    tfvars:
      component_124_name: component_124
      component_124_type: String
      component_124_value: component_124
