component:
  name: component_88
  template:
    resource:
      aws_ssm_parameter:
        component_88:
          name: ${var.component_88_name}
          type: ${var.component_88_type}
          value: ${var.component_88_value}
    variable:
      component_88_name:
        type: string
      component_88_type:
        type: string
      component_88_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_88.id}
      thub_id:
        value: ${aws_ssm_parameter.component_88.id}
      key_id:
        value: ${aws_ssm_parameter.component_88.key_id}
      version:
        value: ${aws_ssm_parameter.component_88.version}
      arn:
        value: ${aws_ssm_parameter.component_88.arn}
    tfvars:
      component_88_name: component_88
      component_88_type: String
      component_88_value: component_88
