component:
  name: snsm_component_80
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_80:
          name: var.snsm_component_80_name
          type: var.snsm_component_80_type
          value: var.snsm_component_80_value
    variable:
      snsm_component_80_name:
        type: string
      snsm_component_80_type:
        type: string
      snsm_component_80_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_80.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_80.id
      key_id:
        value: aws_ssm_parameter.snsm_component_80.key_id
      version:
        value: aws_ssm_parameter.snsm_component_80.version
      arn:
        value: aws_ssm_parameter.snsm_component_80.arn
    tfvars:
      snsm_component_80_name: snsm_component_80
      snsm_component_80_type: String
      snsm_component_80_value: snsm_component_80
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_80/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
