component:
  name: component_37
  template:
    resource:
      aws_ssm_parameter:
        component_37:
          name: ${var.component_37_name}
          type: ${var.component_37_type}
          value: ${var.component_37_value}
    variable:
      component_37_name:
        type: string
      component_37_type:
        type: string
      component_37_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_37.id}
      thub_id:
        value: ${aws_ssm_parameter.component_37.id}
      key_id:
        value: ${aws_ssm_parameter.component_37.key_id}
      version:
        value: ${aws_ssm_parameter.component_37.version}
      arn:
        value: ${aws_ssm_parameter.component_37.arn}
    tfvars:
      component_37_name: component_37
      component_37_type: String
      component_37_value: component_37
