component:
  name: component_119
  template:
    resource:
      aws_ssm_parameter:
        component_119:
          name: ${var.component_119_name}
          type: ${var.component_119_type}
          value: ${var.component_119_value}
    variable:
      component_119_name:
        type: string
      component_119_type:
        type: string
      component_119_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_119.id}
      thub_id:
        value: ${aws_ssm_parameter.component_119.id}
      key_id:
        value: ${aws_ssm_parameter.component_119.key_id}
      version:
        value: ${aws_ssm_parameter.component_119.version}
      arn:
        value: ${aws_ssm_parameter.component_119.arn}
    tfvars:
      component_119_name: component_119
      component_119_type: String
      component_119_value: component_119
