component:
  name: snsm_component_87
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_87:
          name: var.snsm_component_87_name
          type: var.snsm_component_87_type
          value: var.snsm_component_87_value
    variable:
      snsm_component_87_name:
        type: string
      snsm_component_87_type:
        type: string
      snsm_component_87_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_87.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_87.id
      key_id:
        value: aws_ssm_parameter.snsm_component_87.key_id
      version:
        value: aws_ssm_parameter.snsm_component_87.version
      arn:
        value: aws_ssm_parameter.snsm_component_87.arn
    tfvars:
      snsm_component_87_name: snsm_component_87
      snsm_component_87_type: String
      snsm_component_87_value: snsm_component_87
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_87/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
