component:
  name: snsm_component_51
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_51:
          name: var.snsm_component_51_name
          type: var.snsm_component_51_type
          value: var.snsm_component_51_value
    variable:
      snsm_component_51_name:
        type: string
      snsm_component_51_type:
        type: string
      snsm_component_51_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_51.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_51.id
      key_id:
        value: aws_ssm_parameter.snsm_component_51.key_id
      version:
        value: aws_ssm_parameter.snsm_component_51.version
      arn:
        value: aws_ssm_parameter.snsm_component_51.arn
    tfvars:
      snsm_component_51_name: snsm_component_51
      snsm_component_51_type: String
      snsm_component_51_value: snsm_component_51
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_51/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
