component:
  name: snsm_component_1
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_1:
          name: var.snsm_component_1_name
          type: var.snsm_component_1_type
          value: var.snsm_component_1_value
    variable:
      snsm_component_1_name:
        type: string
      snsm_component_1_type:
        type: string
      snsm_component_1_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_1.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_1.id
      key_id:
        value: aws_ssm_parameter.snsm_component_1.key_id
      version:
        value: aws_ssm_parameter.snsm_component_1.version
      arn:
        value: aws_ssm_parameter.snsm_component_1.arn
    tfvars:
      snsm_component_1_name: snsm_component_1
      snsm_component_1_type: String
      snsm_component_1_value: snsm_component_1
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_1/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
