component:
  name: component_18
  template:
    resource:
      aws_ssm_parameter:
        component_18:
          name: ${var.component_18_name}
          type: ${var.component_18_type}
          value: ${var.component_18_value}
    variable:
      component_18_name:
        type: string
      component_18_type:
        type: string
      component_18_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_18.id}
      thub_id:
        value: ${aws_ssm_parameter.component_18.id}
      key_id:
        value: ${aws_ssm_parameter.component_18.key_id}
      version:
        value: ${aws_ssm_parameter.component_18.version}
      arn:
        value: ${aws_ssm_parameter.component_18.arn}
    tfvars:
      component_18_name: component_18
      component_18_type: String
      component_18_value: component_18
