component:
  name: snsm_component_61
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_61:
          name: var.snsm_component_61_name
          type: var.snsm_component_61_type
          value: var.snsm_component_61_value
    variable:
      snsm_component_61_name:
        type: string
      snsm_component_61_type:
        type: string
      snsm_component_61_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_61.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_61.id
      key_id:
        value: aws_ssm_parameter.snsm_component_61.key_id
      version:
        value: aws_ssm_parameter.snsm_component_61.version
      arn:
        value: aws_ssm_parameter.snsm_component_61.arn
    tfvars:
      snsm_component_61_name: snsm_component_61
      snsm_component_61_type: String
      snsm_component_61_value: snsm_component_61
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_61/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
