component:
  name: component_62
  template:
    resource:
      aws_ssm_parameter:
        component_62:
          name: var.component_62_name
          type: var.component_62_type
          value: var.component_62_value
    variable:
      component_62_name:
        type: string
      component_62_type:
        type: string
      component_62_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.component_62.id
      thub_id:
        value: aws_ssm_parameter.component_62.id
      key_id:
        value: aws_ssm_parameter.component_62.key_id
      version:
        value: aws_ssm_parameter.component_62.version
      arn:
        value: aws_ssm_parameter.component_62.arn
    tfvars:
      component_62_name: component_62
      component_62_type: String
      component_62_value: component_62
