component:
  name: component_34
  template:
    resource:
      aws_ssm_parameter:
        component_34:
          name: ${var.component_34_name}
          type: ${var.component_34_type}
          value: ${var.component_34_value}
    variable:
      component_34_name:
        type: string
      component_34_type:
        type: string
      component_34_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_34.id}
      thub_id:
        value: ${aws_ssm_parameter.component_34.id}
      key_id:
        value: ${aws_ssm_parameter.component_34.key_id}
      version:
        value: ${aws_ssm_parameter.component_34.version}
      arn:
        value: ${aws_ssm_parameter.component_34.arn}
    tfvars:
      component_34_name: component_34
      component_34_type: String
      component_34_value: component_34
