component:
  name: snsm_component_12
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_12:
          name: var.snsm_component_12_name
          type: var.snsm_component_12_type
          value: var.snsm_component_12_value
    variable:
      snsm_component_12_name:
        type: string
      snsm_component_12_type:
        type: string
      snsm_component_12_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_12.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_12.id
      key_id:
        value: aws_ssm_parameter.snsm_component_12.key_id
      version:
        value: aws_ssm_parameter.snsm_component_12.version
      arn:
        value: aws_ssm_parameter.snsm_component_12.arn
    tfvars:
      snsm_component_12_name: snsm_component_12
      snsm_component_12_type: String
      snsm_component_12_value: snsm_component_12
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_12/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
