component:
  name: component_76
  template:
    resource:
      aws_ssm_parameter:
        component_76:
          name: ${var.component_76_name}
          type: ${var.component_76_type}
          value: ${var.component_76_value}
    variable:
      component_76_name:
        type: string
      component_76_type:
        type: string
      component_76_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_76.id}
      thub_id:
        value: ${aws_ssm_parameter.component_76.id}
      key_id:
        value: ${aws_ssm_parameter.component_76.key_id}
      version:
        value: ${aws_ssm_parameter.component_76.version}
      arn:
        value: ${aws_ssm_parameter.component_76.arn}
    tfvars:
      component_76_name: component_76
      component_76_type: String
      component_76_value: component_76
