component:
  name: snsm_component_76
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_76:
          name: var.snsm_component_76_name
          type: var.snsm_component_76_type
          value: var.snsm_component_76_value
    variable:
      snsm_component_76_name:
        type: string
      snsm_component_76_type:
        type: string
      snsm_component_76_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_76.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_76.id
      key_id:
        value: aws_ssm_parameter.snsm_component_76.key_id
      version:
        value: aws_ssm_parameter.snsm_component_76.version
      arn:
        value: aws_ssm_parameter.snsm_component_76.arn
    tfvars:
      snsm_component_76_name: snsm_component_76
      snsm_component_76_type: String
      snsm_component_76_value: snsm_component_76
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_76/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
