component:
  name: component_19
  template:
    resource:
      aws_ssm_parameter:
        component_19:
          name: ${var.component_19_name}
          type: ${var.component_19_type}
          value: ${var.component_19_value}
    variable:
      component_19_name:
        type: string
      component_19_type:
        type: string
      component_19_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_19.id}
      thub_id:
        value: ${aws_ssm_parameter.component_19.id}
      key_id:
        value: ${aws_ssm_parameter.component_19.key_id}
      version:
        value: ${aws_ssm_parameter.component_19.version}
      arn:
        value: ${aws_ssm_parameter.component_19.arn}
    tfvars:
      component_19_name: component_19
      component_19_type: String
      component_19_value: component_19
