component:
  name: snsm_component_19
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_19:
          name: var.snsm_component_19_name
          type: var.snsm_component_19_type
          value: var.snsm_component_19_value
    variable:
      snsm_component_19_name:
        type: string
      snsm_component_19_type:
        type: string
      snsm_component_19_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_19.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_19.id
      key_id:
        value: aws_ssm_parameter.snsm_component_19.key_id
      version:
        value: aws_ssm_parameter.snsm_component_19.version
      arn:
        value: aws_ssm_parameter.snsm_component_19.arn
    tfvars:
      snsm_component_19_name: snsm_component_19
      snsm_component_19_type: String
      snsm_component_19_value: snsm_component_19
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_19/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
