component:
  name: snsm_component_73
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_73:
          name: var.snsm_component_73_name
          type: var.snsm_component_73_type
          value: var.snsm_component_73_value
    variable:
      snsm_component_73_name:
        type: string
      snsm_component_73_type:
        type: string
      snsm_component_73_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_73.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_73.id
      key_id:
        value: aws_ssm_parameter.snsm_component_73.key_id
      version:
        value: aws_ssm_parameter.snsm_component_73.version
      arn:
        value: aws_ssm_parameter.snsm_component_73.arn
    tfvars:
      snsm_component_73_name: snsm_component_73
      snsm_component_73_type: String
      snsm_component_73_value: snsm_component_73
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_73/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
