component:
  name: component_67
  template:
    resource:
      aws_ssm_parameter:
        component_67:
          name: var.component_67_name
          type: var.component_67_type
          value: var.component_67_value
    variable:
      component_67_name:
        type: string
      component_67_type:
        type: string
      component_67_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.component_67.id
      thub_id:
        value: aws_ssm_parameter.component_67.id
      key_id:
        value: aws_ssm_parameter.component_67.key_id
      version:
        value: aws_ssm_parameter.component_67.version
      arn:
        value: aws_ssm_parameter.component_67.arn
    tfvars:
      component_67_name: component_67
      component_67_type: String
      component_67_value: component_67
