component:
  name: component_114
  template:
    resource:
      aws_ssm_parameter:
        component_114:
          name: ${var.component_114_name}
          type: ${var.component_114_type}
          value: ${var.component_114_value}
    variable:
      component_114_name:
        type: string
      component_114_type:
        type: string
      component_114_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_114.id}
      thub_id:
        value: ${aws_ssm_parameter.component_114.id}
      key_id:
        value: ${aws_ssm_parameter.component_114.key_id}
      version:
        value: ${aws_ssm_parameter.component_114.version}
      arn:
        value: ${aws_ssm_parameter.component_114.arn}
    tfvars:
      component_114_name: component_114
      component_114_type: String
      component_114_value: component_114
