component:
  name: snsm_component_27
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_27:
          name: var.snsm_component_27_name
          type: var.snsm_component_27_type
          value: var.snsm_component_27_value
    variable:
      snsm_component_27_name:
        type: string
      snsm_component_27_type:
        type: string
      snsm_component_27_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_27.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_27.id
      key_id:
        value: aws_ssm_parameter.snsm_component_27.key_id
      version:
        value: aws_ssm_parameter.snsm_component_27.version
      arn:
        value: aws_ssm_parameter.snsm_component_27.arn
    tfvars:
      snsm_component_27_name: snsm_component_27
      snsm_component_27_type: String
      snsm_component_27_value: snsm_component_27
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_27/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
