component:
  name: component_27
  template:
    resource:
      aws_ssm_parameter:
        component_27:
          name: var.component_27_name
          type: var.component_27_type
          value: var.component_27_value
    variable:
      component_27_name:
        type: string
      component_27_type:
        type: string
      component_27_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.component_27.id
      thub_id:
        value: aws_ssm_parameter.component_27.id
      key_id:
        value: aws_ssm_parameter.component_27.key_id
      version:
        value: aws_ssm_parameter.component_27.version
      arn:
        value: aws_ssm_parameter.component_27.arn
    tfvars:
      component_27_name: component_27
      component_27_type: String
      component_27_value: component_27
