component:
  name: component_7
  template:
    resource:
      aws_ssm_parameter:
        component_7:
          name: var.component_7_name
          type: var.component_7_type
          value: var.component_7_value
    variable:
      component_7_name:
        type: string
      component_7_type:
        type: string
      component_7_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.component_7.id
      thub_id:
        value: aws_ssm_parameter.component_7.id
      key_id:
        value: aws_ssm_parameter.component_7.key_id
      version:
        value: aws_ssm_parameter.component_7.version
      arn:
        value: aws_ssm_parameter.component_7.arn
    tfvars:
      component_7_name: component_7
      component_7_type: String
      component_7_value: component_7