component:
  name: component_81
  template:
    resource:
      aws_ssm_parameter:
        component_81:
          name: ${var.component_81_name}
          type: ${var.component_81_type}
          value: ${var.component_81_value}
    variable:
      component_81_name:
        type: string
      component_81_type:
        type: string
      component_81_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_81.id}
      thub_id:
        value: ${aws_ssm_parameter.component_81.id}
      key_id:
        value: ${aws_ssm_parameter.component_81.key_id}
      version:
        value: ${aws_ssm_parameter.component_81.version}
      arn:
        value: ${aws_ssm_parameter.component_81.arn}
    tfvars:
      component_81_name: component_81
      component_81_type: String
      component_81_value: component_81
