component:
  name: snsm_component_29
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_29:
          name: var.snsm_component_29_name
          type: var.snsm_component_29_type
          value: var.snsm_component_29_value
    variable:
      snsm_component_29_name:
        type: string
      snsm_component_29_type:
        type: string
      snsm_component_29_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_29.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_29.id
      key_id:
        value: aws_ssm_parameter.snsm_component_29.key_id
      version:
        value: aws_ssm_parameter.snsm_component_29.version
      arn:
        value: aws_ssm_parameter.snsm_component_29.arn
    tfvars:
      snsm_component_29_name: snsm_component_29
      snsm_component_29_type: String
      snsm_component_29_value: snsm_component_29
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_29/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
