component:
  name: component_56
  template:
    resource:
      aws_ssm_parameter:
        component_56:
          name: var.component_56_name
          type: var.component_56_type
          value: var.component_56_value
    variable:
      component_56_name:
        type: string
      component_56_type:
        type: string
      component_56_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.component_56.id
      thub_id:
        value: aws_ssm_parameter.component_56.id
      key_id:
        value: aws_ssm_parameter.component_56.key_id
      version:
        value: aws_ssm_parameter.component_56.version
      arn:
        value: aws_ssm_parameter.component_56.arn
    tfvars:
      component_56_name: component_56
      component_56_type: String
      component_56_value: component_56
