component:
  name: component_134
  template:
    resource:
      aws_ssm_parameter:
        component_134:
          name: ${var.component_134_name}
          type: ${var.component_134_type}
          value: ${var.component_134_value}
    variable:
      component_134_name:
        type: string
      component_134_type:
        type: string
      component_134_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_134.id}
      thub_id:
        value: ${aws_ssm_parameter.component_134.id}
      key_id:
        value: ${aws_ssm_parameter.component_134.key_id}
      version:
        value: ${aws_ssm_parameter.component_134.version}
      arn:
        value: ${aws_ssm_parameter.component_134.arn}
    tfvars:
      component_134_name: component_134
      component_134_type: String
      component_134_value: component_134
