component:
  name: component_9
  template:
    resource:
      aws_ssm_parameter:
        component_9:
          name: ${var.component_9_name}
          type: ${var.component_9_type}
          value: ${var.component_9_value}
    variable:
      component_9_name:
        type: string
      component_9_type:
        type: string
      component_9_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_9.id}
      thub_id:
        value: ${aws_ssm_parameter.component_9.id}
      key_id:
        value: ${aws_ssm_parameter.component_9.key_id}
      version:
        value: ${aws_ssm_parameter.component_9.version}
      arn:
        value: ${aws_ssm_parameter.component_9.arn}
    tfvars:
      component_9_name: component_9
      component_9_type: String
      component_9_value: component_9
