component:
  name: snsm_component_18
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_18:
          name: var.snsm_component_18_name
          type: var.snsm_component_18_type
          value: var.snsm_component_18_value
    variable:
      snsm_component_18_name:
        type: string
      snsm_component_18_type:
        type: string
      snsm_component_18_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_18.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_18.id
      key_id:
        value: aws_ssm_parameter.snsm_component_18.key_id
      version:
        value: aws_ssm_parameter.snsm_component_18.version
      arn:
        value: aws_ssm_parameter.snsm_component_18.arn
    tfvars:
      snsm_component_18_name: snsm_component_18
      snsm_component_18_type: String
      snsm_component_18_value: snsm_component_18
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_18/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
