component:
  name: component_188
  template:
    resource:
      aws_ssm_parameter:
        component_188:
          name: ${var.component_188_name}
          type: ${var.component_188_type}
          value: ${var.component_188_value}
    variable:
      component_188_name:
        type: string
      component_188_type:
        type: string
      component_188_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_188.id}
      thub_id:
        value: ${aws_ssm_parameter.component_188.id}
      key_id:
        value: ${aws_ssm_parameter.component_188.key_id}
      version:
        value: ${aws_ssm_parameter.component_188.version}
      arn:
        value: ${aws_ssm_parameter.component_188.arn}
    tfvars:
      component_188_name: component_188
      component_188_type: String
      component_188_value: component_188
