component:
  name: component_21
  template:
    resource:
      aws_ssm_parameter:
        component_21:
          name: ${var.component_21_name}
          type: ${var.component_21_type}
          value: ${var.component_21_value}
    variable:
      component_21_name:
        type: string
      component_21_type:
        type: string
      component_21_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_21.id}
      thub_id:
        value: ${aws_ssm_parameter.component_21.id}
      key_id:
        value: ${aws_ssm_parameter.component_21.key_id}
      version:
        value: ${aws_ssm_parameter.component_21.version}
      arn:
        value: ${aws_ssm_parameter.component_21.arn}
    tfvars:
      component_21_name: component_21
      component_21_type: String
      component_21_value: component_21
