component:
  name: component_95
  template:
    resource:
      aws_ssm_parameter:
        component_95:
          name: var.component_95_name
          type: var.component_95_type
          value: var.component_95_value
    variable:
      component_95_name:
        type: string
      component_95_type:
        type: string
      component_95_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.component_95.id
      thub_id:
        value: aws_ssm_parameter.component_95.id
      key_id:
        value: aws_ssm_parameter.component_95.key_id
      version:
        value: aws_ssm_parameter.component_95.version
      arn:
        value: aws_ssm_parameter.component_95.arn
    tfvars:
      component_95_name: component_95
      component_95_type: String
      component_95_value: component_95
