component:
  name: snsm_component_95
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_95:
          name: var.snsm_component_95_name
          type: var.snsm_component_95_type
          value: var.snsm_component_95_value
    variable:
      snsm_component_95_name:
        type: string
      snsm_component_95_type:
        type: string
      snsm_component_95_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_95.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_95.id
      key_id:
        value: aws_ssm_parameter.snsm_component_95.key_id
      version:
        value: aws_ssm_parameter.snsm_component_95.version
      arn:
        value: aws_ssm_parameter.snsm_component_95.arn
    tfvars:
      snsm_component_95_name: snsm_component_95
      snsm_component_95_type: String
      snsm_component_95_value: snsm_component_95
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_95/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
