component:
  name: snsm_component_82
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_82:
          name: var.snsm_component_82_name
          type: var.snsm_component_82_type
          value: var.snsm_component_82_value
    variable:
      snsm_component_82_name:
        type: string
      snsm_component_82_type:
        type: string
      snsm_component_82_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_82.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_82.id
      key_id:
        value: aws_ssm_parameter.snsm_component_82.key_id
      version:
        value: aws_ssm_parameter.snsm_component_82.version
      arn:
        value: aws_ssm_parameter.snsm_component_82.arn
    tfvars:
      snsm_component_82_name: snsm_component_82
      snsm_component_82_type: String
      snsm_component_82_value: snsm_component_82
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_82/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
