component:
  name: component_90
  template:
    resource:
      aws_ssm_parameter:
        component_90:
          name: var.component_90_name
          type: var.component_90_type
          value: var.component_90_value
    variable:
      component_90_name:
        type: string
      component_90_type:
        type: string
      component_90_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.component_90.id
      thub_id:
        value: aws_ssm_parameter.component_90.id
      key_id:
        value: aws_ssm_parameter.component_90.key_id
      version:
        value: aws_ssm_parameter.component_90.version
      arn:
        value: aws_ssm_parameter.component_90.arn
    tfvars:
      component_90_name: component_90
      component_90_type: String
      component_90_value: component_90
