component:
  name: component_24
  template:
    resource:
      aws_ssm_parameter:
        component_24:
          name: var.component_24_name
          type: var.component_24_type
          value: var.component_24_value
    variable:
      component_24_name:
        type: string
      component_24_type:
        type: string
      component_24_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.component_24.id
      thub_id:
        value: aws_ssm_parameter.component_24.id
      key_id:
        value: aws_ssm_parameter.component_24.key_id
      version:
        value: aws_ssm_parameter.component_24.version
      arn:
        value: aws_ssm_parameter.component_24.arn
    tfvars:
      component_24_name: component_24
      component_24_type: String
      component_24_value: component_24
