component:
  name: component_85
  template:
    resource:
      aws_ssm_parameter:
        component_85:
          name: var.component_85_name
          type: var.component_85_type
          value: var.component_85_value
    variable:
      component_85_name:
        type: string
      component_85_type:
        type: string
      component_85_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.component_85.id
      thub_id:
        value: aws_ssm_parameter.component_85.id
      key_id:
        value: aws_ssm_parameter.component_85.key_id
      version:
        value: aws_ssm_parameter.component_85.version
      arn:
        value: aws_ssm_parameter.component_85.arn
    tfvars:
      component_85_name: component_85
      component_85_type: String
      component_85_value: component_85
