component:
  name: component_79
  template:
    resource:
      aws_ssm_parameter:
        component_79:
          name: var.component_79_name
          type: var.component_79_type
          value: var.component_79_value
    variable:
      component_79_name:
        type: string
      component_79_type:
        type: string
      component_79_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.component_79.id
      thub_id:
        value: aws_ssm_parameter.component_79.id
      key_id:
        value: aws_ssm_parameter.component_79.key_id
      version:
        value: aws_ssm_parameter.component_79.version
      arn:
        value: aws_ssm_parameter.component_79.arn
    tfvars:
      component_79_name: component_79
      component_79_type: String
      component_79_value: component_79
