component:
  name: component_63
  template:
    resource:
      aws_ssm_parameter:
        component_63:
          name: ${var.component_63_name}
          type: ${var.component_63_type}
          value: ${var.component_63_value}
    variable:
      component_63_name:
        type: string
      component_63_type:
        type: string
      component_63_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_63.id}
      thub_id:
        value: ${aws_ssm_parameter.component_63.id}
      key_id:
        value: ${aws_ssm_parameter.component_63.key_id}
      version:
        value: ${aws_ssm_parameter.component_63.version}
      arn:
        value: ${aws_ssm_parameter.component_63.arn}
    tfvars:
      component_63_name: component_63
      component_63_type: String
      component_63_value: component_63
