component:
  name: snsm_component_63
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_63:
          name: var.snsm_component_63_name
          type: var.snsm_component_63_type
          value: var.snsm_component_63_value
    variable:
      snsm_component_63_name:
        type: string
      snsm_component_63_type:
        type: string
      snsm_component_63_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_63.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_63.id
      key_id:
        value: aws_ssm_parameter.snsm_component_63.key_id
      version:
        value: aws_ssm_parameter.snsm_component_63.version
      arn:
        value: aws_ssm_parameter.snsm_component_63.arn
    tfvars:
      snsm_component_63_name: snsm_component_63
      snsm_component_63_type: String
      snsm_component_63_value: snsm_component_63
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_63/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
