component:
  name: component_42
  template:
    resource:
      aws_ssm_parameter:
        component_42:
          name: var.component_42_name
          type: var.component_42_type
          value: var.component_42_value
    variable:
      component_42_name:
        type: string
      component_42_type:
        type: string
      component_42_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.component_42.id
      thub_id:
        value: aws_ssm_parameter.component_42.id
      key_id:
        value: aws_ssm_parameter.component_42.key_id
      version:
        value: aws_ssm_parameter.component_42.version
      arn:
        value: aws_ssm_parameter.component_42.arn
    tfvars:
      component_42_name: component_42
      component_42_type: String
      component_42_value: component_42
