component:
  name: snsm_component_42
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_42:
          name: var.snsm_component_42_name
          type: var.snsm_component_42_type
          value: var.snsm_component_42_value
    variable:
      snsm_component_42_name:
        type: string
      snsm_component_42_type:
        type: string
      snsm_component_42_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_42.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_42.id
      key_id:
        value: aws_ssm_parameter.snsm_component_42.key_id
      version:
        value: aws_ssm_parameter.snsm_component_42.version
      arn:
        value: aws_ssm_parameter.snsm_component_42.arn
    tfvars:
      snsm_component_42_name: snsm_component_42
      snsm_component_42_type: String
      snsm_component_42_value: snsm_component_42
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_42/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
