component:
  name: snsm_component_99
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_99:
          name: var.snsm_component_99_name
          type: var.snsm_component_99_type
          value: var.snsm_component_99_value
    variable:
      snsm_component_99_name:
        type: string
      snsm_component_99_type:
        type: string
      snsm_component_99_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_99.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_99.id
      key_id:
        value: aws_ssm_parameter.snsm_component_99.key_id
      version:
        value: aws_ssm_parameter.snsm_component_99.version
      arn:
        value: aws_ssm_parameter.snsm_component_99.arn
    tfvars:
      snsm_component_99_name: snsm_component_99
      snsm_component_99_type: String
      snsm_component_99_value: snsm_component_99
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_99/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
