component:
  name: component_44
  template:
    resource:
      aws_ssm_parameter:
        component_44:
          name: ${var.component_44_name}
          type: ${var.component_44_type}
          value: ${var.component_44_value}
    variable:
      component_44_name:
        type: string
      component_44_type:
        type: string
      component_44_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_44.id}
      thub_id:
        value: ${aws_ssm_parameter.component_44.id}
      key_id:
        value: ${aws_ssm_parameter.component_44.key_id}
      version:
        value: ${aws_ssm_parameter.component_44.version}
      arn:
        value: ${aws_ssm_parameter.component_44.arn}
    tfvars:
      component_44_name: component_44
      component_44_type: String
      component_44_value: component_44
