component:
  name: component_11
  template:
    resource:
      aws_ssm_parameter:
        component_11:
          name: ${var.component_11_name}
          type: ${var.component_11_type}
          value: ${var.component_11_value}
    variable:
      component_11_name:
        type: string
      component_11_type:
        type: string
      component_11_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_11.id}
      thub_id:
        value: ${aws_ssm_parameter.component_11.id}
      key_id:
        value: ${aws_ssm_parameter.component_11.key_id}
      version:
        value: ${aws_ssm_parameter.component_11.version}
      arn:
        value: ${aws_ssm_parameter.component_11.arn}
    tfvars:
      component_11_name: component_11
      component_11_type: String
      component_11_value: component_11
