component:
  name: snsm_component_49
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_49:
          name: var.snsm_component_49_name
          type: var.snsm_component_49_type
          value: var.snsm_component_49_value
    variable:
      snsm_component_49_name:
        type: string
      snsm_component_49_type:
        type: string
      snsm_component_49_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_49.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_49.id
      key_id:
        value: aws_ssm_parameter.snsm_component_49.key_id
      version:
        value: aws_ssm_parameter.snsm_component_49.version
      arn:
        value: aws_ssm_parameter.snsm_component_49.arn
    tfvars:
      snsm_component_49_name: snsm_component_49
      snsm_component_49_type: String
      snsm_component_49_value: snsm_component_49
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_49/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
