component:
  name: component_49
  template:
    resource:
      aws_ssm_parameter:
        component_49:
          name: ${var.component_49_name}
          type: ${var.component_49_type}
          value: ${var.component_49_value}
    variable:
      component_49_name:
        type: string
      component_49_type:
        type: string
      component_49_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_49.id}
      thub_id:
        value: ${aws_ssm_parameter.component_49.id}
      key_id:
        value: ${aws_ssm_parameter.component_49.key_id}
      version:
        value: ${aws_ssm_parameter.component_49.version}
      arn:
        value: ${aws_ssm_parameter.component_49.arn}
    tfvars:
      component_49_name: component_49
      component_49_type: String
      component_49_value: component_49
