component:
  name: snsm_component_53
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_53:
          name: var.snsm_component_53_name
          type: var.snsm_component_53_type
          value: var.snsm_component_53_value
    variable:
      snsm_component_53_name:
        type: string
      snsm_component_53_type:
        type: string
      snsm_component_53_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_53.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_53.id
      key_id:
        value: aws_ssm_parameter.snsm_component_53.key_id
      version:
        value: aws_ssm_parameter.snsm_component_53.version
      arn:
        value: aws_ssm_parameter.snsm_component_53.arn
    tfvars:
      snsm_component_53_name: snsm_component_53
      snsm_component_53_type: String
      snsm_component_53_value: snsm_component_53
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_53/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
