component:
  name: snsm_component_22
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_22:
          name: var.snsm_component_22_name
          type: var.snsm_component_22_type
          value: var.snsm_component_22_value
    variable:
      snsm_component_22_name:
        type: string
      snsm_component_22_type:
        type: string
      snsm_component_22_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_22.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_22.id
      key_id:
        value: aws_ssm_parameter.snsm_component_22.key_id
      version:
        value: aws_ssm_parameter.snsm_component_22.version
      arn:
        value: aws_ssm_parameter.snsm_component_22.arn
    tfvars:
      snsm_component_22_name: snsm_component_22
      snsm_component_22_type: String
      snsm_component_22_value: snsm_component_22
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_22/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
