component:
  name: component_91
  template:
    resource:
      aws_ssm_parameter:
        component_91:
          name: var.component_91_name
          type: var.component_91_type
          value: var.component_91_value
    variable:
      component_91_name:
        type: string
      component_91_type:
        type: string
      component_91_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.component_91.id
      thub_id:
        value: aws_ssm_parameter.component_91.id
      key_id:
        value: aws_ssm_parameter.component_91.key_id
      version:
        value: aws_ssm_parameter.component_91.version
      arn:
        value: aws_ssm_parameter.component_91.arn
    tfvars:
      component_91_name: component_91
      component_91_type: String
      component_91_value: component_91
