component:
  name: snsm_component_15
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_15:
          name: var.snsm_component_15_name
          type: var.snsm_component_15_type
          value: var.snsm_component_15_value
    variable:
      snsm_component_15_name:
        type: string
      snsm_component_15_type:
        type: string
      snsm_component_15_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_15.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_15.id
      key_id:
        value: aws_ssm_parameter.snsm_component_15.key_id
      version:
        value: aws_ssm_parameter.snsm_component_15.version
      arn:
        value: aws_ssm_parameter.snsm_component_15.arn
    tfvars:
      snsm_component_15_name: snsm_component_15
      snsm_component_15_type: String
      snsm_component_15_value: snsm_component_15
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_15/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
