component:
  name: snsm_component_84
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_84:
          name: var.snsm_component_84_name
          type: var.snsm_component_84_type
          value: var.snsm_component_84_value
    variable:
      snsm_component_84_name:
        type: string
      snsm_component_84_type:
        type: string
      snsm_component_84_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_84.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_84.id
      key_id:
        value: aws_ssm_parameter.snsm_component_84.key_id
      version:
        value: aws_ssm_parameter.snsm_component_84.version
      arn:
        value: aws_ssm_parameter.snsm_component_84.arn
    tfvars:
      snsm_component_84_name: snsm_component_84
      snsm_component_84_type: String
      snsm_component_84_value: snsm_component_84
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_84/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
