component:
  name: snsm_component_40
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_40:
          name: var.snsm_component_40_name
          type: var.snsm_component_40_type
          value: var.snsm_component_40_value
    variable:
      snsm_component_40_name:
        type: string
      snsm_component_40_type:
        type: string
      snsm_component_40_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_40.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_40.id
      key_id:
        value: aws_ssm_parameter.snsm_component_40.key_id
      version:
        value: aws_ssm_parameter.snsm_component_40.version
      arn:
        value: aws_ssm_parameter.snsm_component_40.arn
    tfvars:
      snsm_component_40_name: snsm_component_40
      snsm_component_40_type: String
      snsm_component_40_value: snsm_component_40
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_40/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
