component:
  name: component_54
  template:
    resource:
      aws_ssm_parameter:
        component_54:
          name: var.component_54_name
          type: var.component_54_type
          value: var.component_54_value
    variable:
      component_54_name:
        type: string
      component_54_type:
        type: string
      component_54_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.component_54.id
      thub_id:
        value: aws_ssm_parameter.component_54.id
      key_id:
        value: aws_ssm_parameter.component_54.key_id
      version:
        value: aws_ssm_parameter.component_54.version
      arn:
        value: aws_ssm_parameter.component_54.arn
    tfvars:
      component_54_name: component_54
      component_54_type: String
      component_54_value: component_54
