component:
  name: component_61
  template:
    resource:
      aws_ssm_parameter:
        component_61:
          name: ${var.component_61_name}
          type: ${var.component_61_type}
          value: ${var.component_61_value}
    variable:
      component_61_name:
        type: string
      component_61_type:
        type: string
      component_61_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_61.id}
      thub_id:
        value: ${aws_ssm_parameter.component_61.id}
      key_id:
        value: ${aws_ssm_parameter.component_61.key_id}
      version:
        value: ${aws_ssm_parameter.component_61.version}
      arn:
        value: ${aws_ssm_parameter.component_61.arn}
    tfvars:
      component_61_name: component_61
      component_61_type: String
      component_61_value: component_61
