component:
  name: component_13
  template:
    resource:
      aws_ssm_parameter:
        component_13:
          name: var.component_13_name
          type: var.component_13_type
          value: var.component_13_value
    variable:
      component_13_name:
        type: string
      component_13_type:
        type: string
      component_13_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.component_13.id
      thub_id:
        value: aws_ssm_parameter.component_13.id
      key_id:
        value: aws_ssm_parameter.component_13.key_id
      version:
        value: aws_ssm_parameter.component_13.version
      arn:
        value: aws_ssm_parameter.component_13.arn
    tfvars:
      component_13_name: component_13
      component_13_type: String
      component_13_value: component_13
