component:
  name: component_82
  template:
    resource:
      aws_ssm_parameter:
        component_82:
          name: var.component_82_name
          type: var.component_82_type
          value: var.component_82_value
    variable:
      component_82_name:
        type: string
      component_82_type:
        type: string
      component_82_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.component_82.id
      thub_id:
        value: aws_ssm_parameter.component_82.id
      key_id:
        value: aws_ssm_parameter.component_82.key_id
      version:
        value: aws_ssm_parameter.component_82.version
      arn:
        value: aws_ssm_parameter.component_82.arn
    tfvars:
      component_82_name: component_82
      component_82_type: String
      component_82_value: component_82
