component:
  name: component_32
  template:
    resource:
      aws_ssm_parameter:
        component_32:
          name: ${var.component_32_name}
          type: ${var.component_32_type}
          value: ${var.component_32_value}
    variable:
      component_32_name:
        type: string
      component_32_type:
        type: string
      component_32_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_32.id}
      thub_id:
        value: ${aws_ssm_parameter.component_32.id}
      key_id:
        value: ${aws_ssm_parameter.component_32.key_id}
      version:
        value: ${aws_ssm_parameter.component_32.version}
      arn:
        value: ${aws_ssm_parameter.component_32.arn}
    tfvars:
      component_32_name: component_32
      component_32_type: String
      component_32_value: component_32
