component:
  name: snsm_component_32
  template:
    resource:
      aws_ssm_parameter:
        snsm_component_32:
          name: var.snsm_component_32_name
          type: var.snsm_component_32_type
          value: var.snsm_component_32_value
    variable:
      snsm_component_32_name:
        type: string
      snsm_component_32_type:
        type: string
      snsm_component_32_value:
        type: string
    output:
      id:
        value: aws_ssm_parameter.snsm_component_32.id
      thub_id:
        value: aws_ssm_parameter.snsm_component_32.id
      key_id:
        value: aws_ssm_parameter.snsm_component_32.key_id
      version:
        value: aws_ssm_parameter.snsm_component_32.version
      arn:
        value: aws_ssm_parameter.snsm_component_32.arn
    tfvars:
      snsm_component_32_name: snsm_component_32
      snsm_component_32_type: String
      snsm_component_32_value: snsm_component_32
    terraform:
      backend:
        s3:
          key: terraform/cloud_deployer_demo/snsm_component_32/terraform.tfstate
          bucket: data-lake-terrahub-us-east-1
          region: us-east-1
