component:
  name: component_94
  template:
    resource:
      aws_ssm_parameter:
        component_94:
          name: ${var.component_94_name}
          type: ${var.component_94_type}
          value: ${var.component_94_value}
    variable:
      component_94_name:
        type: string
      component_94_type:
        type: string
      component_94_value:
        type: string
    output:
      id:
        value: ${aws_ssm_parameter.component_94.id}
      thub_id:
        value: ${aws_ssm_parameter.component_94.id}
      key_id:
        value: ${aws_ssm_parameter.component_94.key_id}
      version:
        value: ${aws_ssm_parameter.component_94.version}
      arn:
        value: ${aws_ssm_parameter.component_94.arn}
    tfvars:
      component_94_name: component_94
      component_94_type: String
      component_94_value: component_94
